apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ quote .Values.favorite.drink }}
  food: {{ .Values.favorite.food | upper | quote }}
  book: {{ .Values.favorite.book | repeat 5 | upper | quote }}
  drink1: {{ .Values.favorite.drink1 | default "tea" }}
  drink2: {{ .Values.favorite.drink2 | default (printf "%s-water" (include "fullname" .)) }}